### PR TITLE
changed mockedData at QuestionsList.spec.jsx

### LINKED ISSUE #1183: (SP:1) Fixed test Questions
image

### PR DESCRIPTION
**Pull request by OlyaKorchan**
Changed mocked data. Items changed to answers, _id added to question object 
Fixes #1183 

Test result after data change:
Знімок екрана 2023-09-27 о 17 38 21

### CODE REVIEW

**Review by abalanovsky — APPROVED** [review]

**Comment by mxrcury** [comment]
I think it would be good to attach screenshots to description of ran `QuestionsList.spec.jsx` test before and after your fix

**Comment by OlyaKorchan** [comment]
1) Wrong mockedItems in QuestionsList.spec.jsx
Знімок екрана 2023-09-27 о 16 04 25
2) Changed data
Знімок екрана 2023-09-27 о 16 07 21

**Review by Mav-Ivan — APPROVED** [review]

**Comment by OlyaKorchan** [comment]
1) Tests before fix (QuestionsList cannot render Question because of invalid mocked data)
Знімок екрана 2023-09-27 о 17 42 26
2) Tests after changing data
Знімок екрана 2023-09-27 о 17 38 21

**Review by Tolik170 — APPROVED** [review]

**Review by ArturBekhDEV — APPROVED** [review]

**Review by maarekua — APPROVED** [review]

**Comment by OlyaKorchan** [comment]
Fixed in #1208

**Pull request closed without merging**
